#!/bin/sh
# Start DOSBox, mount the disk with the program and start the objective program

dosbox &
sleep 2

xdotool key "M"
xdotool key "O"
xdotool key "U"
xdotool key "N"
xdotool key "T"
xdotool key "space"
xdotool key "C"
xdotool key "space"
xdotool key "slash"
xdotool key "h"
xdotool key "o"
xdotool key "m"
xdotool key "e"
xdotool key "slash"
xdotool key "g"
xdotool key "u"
xdotool key "i"
xdotool key "l"
xdotool key "l"
xdotool key "e"
xdotool key "r"
xdotool key "m"
xdotool key "o"
xdotool key "slash"
xdotool key "period"
xdotool key "d"
xdotool key "o"
xdotool key "s"
xdotool key "b"
xdotool key "o"
xdotool key "x"
xdotool key "slash"
xdotool key "c"
xdotool key "Return"

xdotool key "C"
xdotool key "colon"
xdotool key "Return"

xdotool key "G"
xdotool key "W"
xdotool key "B"
xdotool key "A"
xdotool key "S"
xdotool key "I"
xdotool key "C"
xdotool key "period"
xdotool key "B"
xdotool key "A"
xdotool key "T"
xdotool key "Return"

wait
